title: Adv web programming
email: p.dicarlo@me.com
description: >- # this means to ignore newlines until "baseurl:"
  Used for adv web programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phillipdicarlo.github.io" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true

header_pages:
  - secret-page.md
  - about.markdown

# Featured Post
featured_post: perfect-forwarding

# future: false

# Social
# twitter_username: 
github_username:  PhillipDiCarlo
#linkedin_username: taylorhe

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag
